# ==============================================================================
# OSSA v0.1.8 MCP-Integrated Agent Example
# Open Standards for Scalable Agents with Model Context Protocol Support
# ==============================================================================

apiVersion: open-standards-scalable-agents/v0.1.8
kind: Agent

metadata:
  name: ossa-mcp-validator
  version: "0.1.8"
  labels:
    tier: advanced
    domain: validation
    integration: mcp
  annotations:
    ossa.io/conformance-level: "advanced"
    ossa.io/mcp-version: "0.2.6"
    ossa.io/transport: "stdio"
    ossa.io/created: "2025-09-03"
  description: |
    OSSA validation agent with Model Context Protocol integration.
    Provides OSSA configuration validation, analysis, and examples
    via MCP stdio transport for Claude Desktop and other MCP clients.

spec:
  agent:
    name: "OSSA MCP Validator"
    expertise: "OSSA configuration validation and analysis via MCP protocol"
    version: "0.1.8"

  capabilities:
    - name: validate-ossa-config
      description: "Validates OSSA agent configuration files against v0.1.8 specification"
      parameters:
        filePath:
          type: string
          description: "Path to OSSA configuration file (.yml or .yaml)"
          required: true
    
    - name: list-ossa-examples
      description: "Lists and describes available OSSA example configurations"
      parameters:
        examplesDir:
          type: string
          description: "Directory containing examples"
          default: "./examples"
    
    - name: analyze-ossa-capabilities
      description: "Analyzes agent capabilities and framework compatibility"
      parameters:
        filePath:
          type: string
          description: "Path to OSSA configuration file"
          required: true

  frameworks:
    mcp:
      enabled: true
      transport: stdio
      version: "0.2.6"
      server: "lib/mcp/servers/ossa-validator.js"
      capabilities:
        - tools
      tools:
        - validate-ossa-config
        - list-ossa-examples
        - analyze-ossa-capabilities
    
    langchain:
      enabled: true
      integration: "tool"
    
    crewai:
      enabled: true
      integration: "tool"

  discovery:
    uadp:
      enabled: true
      tags: ["ossa", "validation", "mcp", "standards"]
      protocols:
        - mcp-stdio
        - http-api

  execution:
    runtime: node
    version: ">=18.0.0"
    entry: "lib/mcp/servers/ossa-validator.js"
    transport:
      - stdio
      - http
    
  security:
    sandbox: false
    permissions:
      - read-files
      - access-examples
    validation:
      - yaml-schema
      - ossa-conformance

# ==============================================================================
# MCP Integration Features:
# 1. stdio transport protocol for Claude Desktop
# 2. Three validation tools available via MCP
# 3. Full OSSA v0.1.8 compliance validation
# 4. Examples directory integration
# 5. Capability analysis and reporting
# ==============================================================================