apiVersion: "openapi-ai-agents/v0.1.0"
kind: "Agent"
metadata:
  name: "agent-registry"
  version: "1.0.0"
  namespace: "oaas-services"
  labels:
    domain: "registry"
    certification-level: "gold"
    compliance: "OpenAPI_AI_Agents_Standard"
  annotations:
    agent.uadp/discovery-priority: "critical"
    agent.uadp/context-aware: "true"
    agent.uadp/workspace-enabled: "true"

spec:
  description: "Central agent registry service for workspace-wide agent management"

  capabilities:
    primary:
      - "agent_registration"
      - "capability_indexing"
      - "health_monitoring"
      - "metadata_management"
    secondary:
      - "search_optimization"
      - "version_management"
      - "compliance_tracking"

  protocols:
    supported: ["openapi", "mcp", "uadp", "a2a"]
    primary: "openapi"
    bridges:
      mcp:
        enabled: true
        version: "2024-11-05"
        capabilities: ["tools", "resources", "prompts"]
      uadp:
        enabled: true
        discovery: "automatic"
        context_sharing: "enabled"

  resource_requirements:
    memory: "2Gi"
    cpu: "500m"
    storage: "10Gi"
    network: "1Gbps"

  scaling:
    min_replicas: 2
    max_replicas: 5
    target_cpu: 70
    target_memory: 80

  security:
    authentication:
      methods: ["api_key", "jwt", "oauth2"]
      required: true
    authorization:
      model: "rbac"
      roles: ["registry", "admin", "service"]
    rate_limiting:
      requests_per_minute: 2000
      burst_allowance: 200
      per_user_limit: 200
    encryption:
      at_rest: true
      in_transit: "tls_1_3"
    audit_logging: true

  performance:
    token_optimization:
      enabled: true
      target_savings: "35-45%"
      strategies:
        - "request_deduplication"
        - "response_compression"
        - "context_window_optimization"
        - "smart_caching"
    caching:
      enabled: true
      ttl: 3600
      levels: ["request", "computation", "result"]
    monitoring:
      metrics: true
      tracing: true
      health_checks: true

  compliance:
    frameworks:
      - "iso_42001"
      - "nist_ai_rmf"
      - "eu_ai_act"
    certification_level: "gold"
    audit_trail: true
    data_governance: true

  api:
    specification: "./openapi.yaml"
    base_url: "http://localhost:8081/api/v1"
    version: "1.0.0"

status:
  phase: "ready"
  conditions:
    - type: "ready"
      status: "true"
      last_transition_time: "2024-08-26T12:00:00Z"
  deployment:
    replicas: 2
    available_replicas: 2
    ready_replicas: 2
