apiVersion: open-standards-scalable-agents/v0.1.2
kind: Agent
metadata:
  name: data-analyzer
  version: "1.0.0"
  namespace: default
  labels:
    tier: core
    domain: analytics
  annotations:
    ossa.io/conformance-level: "core"
    ossa.io/migration-date: "2024-01-15"
    ossa.io/source-format: "oaas"
spec:
  agent:
    name: "Data Analysis Agent"
    expertise: "Specialized in data analysis, statistical computing, and insight generation from structured and unstructured datasets"
    description: "A core-level agent focused on providing comprehensive data analysis capabilities with universal framework compatibility"
  
  capabilities:
    - name: analyze_dataset
      description: "Analyze datasets and generate statistical insights"
      frameworks: ["mcp", "langchain", "openai"]
    
    - name: generate_visualizations
      description: "Create charts and visualizations from data"
      frameworks: ["mcp", "crewai"]
    
    - name: detect_patterns
      description: "Identify patterns and anomalies in data"
      frameworks: ["mcp", "langchain", "crewai"]
  
  frameworks:
    mcp:
      enabled: true
      config:
        tools: ["analyze", "visualize", "pattern_detect"]
    
    langchain:
      enabled: true
      integration: "tools"
    
    crewai:
      enabled: true
      role: "data_analyst"
  
  discovery:
    uadp:
      enabled: true
      tags: ["analytics", "data", "statistics", "patterns"]
      priority: 75
  
  context:
    paths:
      - path: "./data"
        description: "Data files and datasets"
        type: "data"
      - path: "./notebooks"
        description: "Analysis notebooks and examples"
        type: "docs"
      - path: "./src"
        description: "Analysis algorithms and utilities"
        type: "code"