apiVersion: open-standards-scalable-agents/v0.1.2
kind: Agent
metadata:
  name: enterprise-processor
  version: "2.1.0"
  namespace: production
  labels:
    tier: governed
    domain: enterprise
    environment: production
  annotations:
    ossa.io/conformance-level: "governed"
    ossa.io/migration-date: "2024-01-15"
    ossa.io/source-format: "langchain"
    enterprise.io/cost-center: "IT-AI-001"
    enterprise.io/owner: "ai-platform-team"
spec:
  agent:
    name: "Enterprise Processing Agent"
    expertise: "Enterprise-grade document processing, workflow automation, and secure data handling with comprehensive audit trails"
    description: "A governed-level agent designed for production enterprise environments with security, monitoring, and compliance features"
  
  capabilities:
    - name: process_documents
      description: "Process enterprise documents with security and audit"
      frameworks: ["mcp", "langchain", "crewai", "openai"]
      input_schema: "./schemas/document-input.json"
      output_schema: "./schemas/document-output.json"
      sla:
        response_time_ms: 5000
        availability: "99.9%"
        throughput:
          requests_per_minute: 100
    
    - name: automate_workflow
      description: "Automate business workflows with approval gates"
      frameworks: ["mcp", "langchain", "crewai"]
      input_schema: "./schemas/workflow-input.json"
      output_schema: "./schemas/workflow-output.json"
      sla:
        response_time_ms: 10000
        availability: "99.5%"
        throughput:
          requests_per_minute: 50
    
    - name: generate_reports
      description: "Generate compliance and business reports"
      frameworks: ["mcp", "openai", "anthropic"]
      input_schema: "./schemas/report-input.json"
      output_schema: "./schemas/report-output.json"
      sla:
        response_time_ms: 15000
        availability: "99.9%"
        throughput:
          requests_per_minute: 25
  
  frameworks:
    mcp:
      enabled: true
      config:
        tools: ["process", "automate", "report"]
        security:
          require_auth: true
    
    langchain:
      enabled: true
      integration: "agents"
      config:
        memory_type: "persistent"
        tools_config:
          max_concurrent: 10
    
    crewai:
      enabled: true
      role: "enterprise_processor"
      config:
        hierarchy: "manager"
  
  security:
    authentication:
      required: true
      methods: ["jwt", "oauth2", "api_key"]
      providers: ["okta", "azure_ad", "internal_ldap"]
    
    authorization:
      enabled: true
      model: "rbac"
      policies:
        - role: "admin"
          permissions: ["read", "write", "execute", "manage"]
        - role: "processor"
          permissions: ["read", "execute"]
        - role: "viewer"
          permissions: ["read"]
    
    encryption:
      in_transit: true
      at_rest: true
      algorithms: ["AES-256", "RSA-2048"]
  
  orchestration:
    patterns: ["sequential", "parallel", "circuit_breaker"]
    timeout: "60s"
    retry:
      max_attempts: 3
      backoff_strategy: "exponential"
      initial_delay: "2s"
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout: "120s"
  
  monitoring:
    enabled: true
    metrics: ["response_time", "throughput", "error_rate", "availability", "resource_usage"]
    alerts:
      - name: "high_error_rate"
        condition: "greater_than"
        threshold: 0.05
        duration: "5m"
      - name: "slow_response"
        condition: "greater_than"
        threshold: 10000
        duration: "2m"
  
  api:
    openapi: "./openapi.yaml"
    base_path: "/api/v1"
    rate_limiting:
      requests_per_minute: 1000
      burst_size: 100
  
  discovery:
    uadp:
      enabled: true
      tags: ["enterprise", "processing", "workflows", "reports", "secure"]
      priority: 90
  
  context:
    paths:
      - path: "./schemas"
        description: "JSON Schema definitions"
        type: "config"
      - path: "./workflows"
        description: "Business workflow definitions"
        type: "config"
      - path: "./reports"
        description: "Report templates and configurations"
        type: "config"
      - path: "./src"
        description: "Enterprise processing logic"
        type: "code"
      - path: "./tests"
        description: "Comprehensive test suites"
        type: "tests"