apiVersion: open-standards-scalable-agents/v0.1.2
kind: OrchestrationRules
metadata:
  name: enterprise-orchestration-patterns
  description: "Enterprise orchestration rules for complex multi-agent workflows"
  labels:
    environment: production
    version: "v2.1"
spec:
  patterns:
    - name: "document-processing-pipeline"
      type: "sequential"
      description: "Sequential document processing with validation and enrichment"
      trigger:
        conditions:
          - field: "request.type"
            operator: "equals"
            value: "document_processing"
          - field: "request.priority"
            operator: "greater_than"
            value: 5
        logic: "and"
      stages:
        - agent: "document-validator"
          capability: "validate_document"
          timeout: "30s"
          retry:
            max_attempts: 2
            backoff: "exponential"
          fallback: "basic-validator"
        
        - agent: "content-extractor"
          capability: "extract_content"
          timeout: "60s"
          retry:
            max_attempts: 3
            backoff: "linear"
        
        - agent: "data-enricher"
          capability: "enrich_content"
          timeout: "45s"
        
        - agent: "compliance-checker"
          capability: "check_compliance"
          timeout: "30s"
          fallback: "manual-review"
      
      rollback_on_failure: true
    
    - name: "parallel-analysis"
      type: "parallel"
      description: "Parallel analysis by multiple specialized agents"
      trigger:
        conditions:
          - field: "request.type"
            operator: "equals"
            value: "comprehensive_analysis"
      agents: ["sentiment-analyzer", "risk-assessor", "quality-checker", "bias-detector"]
      capabilities: ["analyze", "assess", "check", "detect"]
      aggregation: "consensus"
      timeout: "180s"
      partial_failure_handling: "continue"
    
    - name: "research-coordination"
      type: "fanout"
      description: "Coordinate research across specialist agents"
      trigger:
        conditions:
          - field: "request.type"
            operator: "equals"
            value: "research_task"
      coordinator: "research-coordinator"
      workers: ["technical-researcher", "market-analyst", "legal-researcher", "patent-searcher"]
      distribution_strategy: "capability_based"
      aggregation_strategy: "weighted"
      fan_in_timeout: "300s"
    
    - name: "critical-system-protection"
      type: "circuit_breaker"
      description: "Protect critical processing agent from overload"
      agent: "critical-processor"
      failure_threshold: 3
      recovery_timeout: "180s"
      monitoring_window: "60s"
      fallback_agent: "backup-processor"
    
    - name: "transaction-workflow"
      type: "saga"
      description: "Multi-step transaction with compensation"
      transactions:
        - step: "validate_request"
          agent: "validator"
          capability: "validate"
          compensation:
            agent: "validator"
            capability: "invalidate"
          timeout: "30s"
        
        - step: "allocate_resources"
          agent: "resource-manager"
          capability: "allocate"
          compensation:
            agent: "resource-manager"
            capability: "deallocate"
          timeout: "60s"
        
        - step: "process_transaction"
          agent: "transaction-processor"
          capability: "process"
          compensation:
            agent: "transaction-processor"
            capability: "rollback"
          timeout: "120s"
        
        - step: "send_notification"
          agent: "notification-service"
          capability: "notify"
          compensation:
            agent: "notification-service"
            capability: "cancel_notification"
          timeout: "15s"
      
      isolation_level: "read_committed"
    
    - name: "stream-processing-pipeline"
      type: "pipeline"
      description: "Real-time stream processing pipeline"
      stages:
        - name: "ingestion"
          agent: "stream-ingester"
          capability: "ingest"
          batch_size: 100
          parallelism: 5
        
        - name: "transformation"
          agent: "data-transformer"
          capability: "transform"
          batch_size: 50
          parallelism: 10
        
        - name: "enrichment"
          agent: "data-enricher"
          capability: "enrich"
          batch_size: 25
          parallelism: 8
        
        - name: "storage"
          agent: "data-storer"
          capability: "store"
          batch_size: 200
          parallelism: 3
      
      backpressure:
        enabled: true
        buffer_size: 1000
        strategy: "block"
  
  defaults:
    timeout: "60s"
    retry:
      max_attempts: 3
      backoff: "exponential"
      initial_delay: "1s"
    monitoring:
      enabled: true
      metrics: ["latency", "throughput", "error_rate", "success_rate"]