apiVersion: open-standards-scalable-agents/v0.1.2
kind: Workspace
metadata:
  name: enterprise-ai-workspace
  version: "1.0.0"
  description: "Enterprise AI workspace with multi-agent orchestration and governance"
  labels:
    environment: production
    organization: acme-corp
    compliance: "iso-42001"
spec:
  discovery:
    uadp:
      enabled: true
      scan_patterns:
        - "**/.agents/agent.yml"
        - "**/.agents/*/agent.yml"
        - "**/agents.yml"
      exclude_patterns:
        - "**/node_modules/**"
        - "**/.git/**"
        - "**/target/**"
        - "**/build/**"
      scan_interval: "3m"
      max_depth: 6
    cache:
      enabled: true
      ttl: "30m"
  
  agents:
    - id: "data-analyzer"
      path: "./analytics/.agents/data-analyzer/"
      enabled: true
      priority: 80
      tags: ["analytics", "data", "core"]
    
    - id: "enterprise-processor"
      path: "./processing/.agents/enterprise-processor/"
      enabled: true
      priority: 95
      tags: ["enterprise", "processing", "governed"]
    
    - id: "compliance-auditor"
      path: "./compliance/.agents/compliance-auditor/"
      enabled: true
      priority: 100
      tags: ["compliance", "audit", "advanced"]
    
    - id: "security-scanner"
      path: "./security/.agents/security-scanner/"
      enabled: true
      priority: 90
      tags: ["security", "scanning", "governed"]
  
  orchestration:
    default_strategy: "capability_match"
    routing:
      rules:
        - pattern: "analyze.*data"
          agents: ["data-analyzer"]
          strategy: "primary_fallback"
        
        - pattern: "process.*document"
          agents: ["enterprise-processor"]
          strategy: "sequential"
        
        - pattern: "audit|compliance"
          agents: ["compliance-auditor", "security-scanner"]
          strategy: "parallel"
        
        - pattern: "security.*scan"
          agents: ["security-scanner", "enterprise-processor"]
          strategy: "fanout"
    
    aggregation:
      strategy: "consensus"
      conflict_resolution: "weighted"
    
    timeout: "120s"
  
  context:
    shared_resources:
      - name: "enterprise-knowledge-base"
        type: "knowledge_base"
        path: "./shared/knowledge/"
        description: "Shared enterprise knowledge and policies"
      
      - name: "compliance-database"
        type: "data_source"
        path: "./shared/compliance/"
        description: "Compliance frameworks and requirements"
      
      - name: "security-policies"
        type: "config"
        path: "./shared/security/"
        description: "Enterprise security policies and configurations"
      
      - name: "shared-models"
        type: "model"
        path: "./shared/models/"
        description: "Shared AI models and embeddings"
    
    environment_variables:
      WORKSPACE_ENV: "production"
      LOG_LEVEL: "info"
      AUDIT_ENABLED: "true"
      COMPLIANCE_MODE: "strict"
  
  monitoring:
    enabled: true
    metrics:
      collection_interval: "30s"
      retention_period: "30d"